# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed11b68facebd4d9811a93646e3aebde6eb1f4c51c722611d8312eec25deb42f3ba5caac9b311731c2e3b398e4d4c0f1cf1a180dbfd2d1077e5cbe6951f95b7

test:
  secret_key_base: 65c8079ed4d0d489cf5463601af0f259fe7a8c1aae90fae20db1e00ab7e3791db6eb8f90be165f0389fe603c7c24d6e0ee32bc1b7761815d11508bd0cea124b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
